---
- name: Install and configure Apache HTTP Server (httpd)
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache HTTP Server (httpd)
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
    
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
